#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                         - Moving  Forward -                                            *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot forward for a designated amount of time.                                 *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  To change the forward movement's speed, replace the two "100"'s with the desired speed number.  *|
|*    2)  To change the duration of the movement, replace the "4000" with the desired number of           *|
|*        milliseconds.                                                                                   *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/
bool complete = false;
bool lineFollowing = false;
int count=0;
int sens=0;
void followLine() {
	string value = "";

	if (SensorValue(colorSensor) < 2600) {
		motor[motorC] = 25;
		motor[motorB] = 20;
		stringFormat(value, "%d", SensorValue(colorSensor));
		displayCenteredBigTextLine(4, value);
		}
		else if (SensorValue(colorSensor) > 2610 && SensorValue(colorSensor) < 2800) {
		}else {
		if (SensorValue(colorSensor) < 2800) {
			motor[motorC] = -15;
			motor[motorB] = 15;
			sleep(200);
			for (int i = 0; i < 1500; i++) {
				motor[motorC] = 25;
				motor[motorB] = 25;
			}

			stringFormat(value, "%d", SensorValue(colorSensor));
			displayCenteredBigTextLine(4, value);
		}
	}
}

void straightLine() {
	motor[motorC] = 25;
	motor[motorB] = 25;
		lineFollowing = true;
		complete = true;
	}

task main()
{
	while(count<3) {
		sens= SensorValue(colorSensor);
		followLine();
		if (SensorValue(colorSensor) > 2640 && SensorValue(colorSensor) < 2800){
			count++;
			if (count !=2)
			{
			for (int i = 0; i<500; i++){
				motor[motorC] = 25;
				motor[motorB] = 25;
			}
		}
		else {
			motor[motorC] = 5;
				motor[motorB] = 25;
	sleep (1000);
		}
			sleep(1000);
		}
	}
	motor[motorC] = 0;
	motor[motorB] = 0;
	sleep (3000);
	playImmediateTone(256,80);
				motor[motorC] = 35;
				motor[motorB] = 0;
	sleep (700);
	motor[motorD] = 25;
	sleep (100);
	motor[motorD] = 0;
	for (int i = 0; i<2000; i++)
	{
		sens= SensorValue(colorSensor);
	straightLine();
	sleep(1);
}
	}
