#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                         - Moving  Forward -                                            *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your robot forward for a designated amount of time.                                 *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  To change the forward movement's speed, replace the two "100"'s with the desired speed number.  *|
|*    2)  To change the duration of the movement, replace the "4000" with the desired number of           *|
|*        milliseconds.                                                                                   *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/
bool complete = false;
int greenLinesPassed = 0;
bool lineFollowing = false;

void followLine() {
	string value = "";

	if (SensorValue(colorSensor) < 2550) {
		motor[motorC] = 25;
		motor[motorB] = 20;
		stringFormat(value, "%d", SensorValue(colorSensor));
		displayCenteredBigTextLine(4, value);
	} else if (SensorValue(colorSensor) > 2550 && SensorValue(colorSensor) < 2700) {
		greenLinesPassed++;
		motor[motorC] = 0;
		motor[motorB] = 0;
		stringFormat(value, "%d", greenLinesPassed);
			displayCenteredBigTextLine(4, value);
		sleep(4000);
		if (greenLinesPassed == 2) {
			for (int i = 0; i < 2500; i++) {
				motor[motorC] = -20;
				motor[motorB] = 20;
			}
		} else if (greenLinesPassed == 3) {
			stringFormat(value, "%d", greenLinesPassed);
			displayCenteredBigTextLine(4, value);
			motor[motorC] = 0;
			motor[motorB] = 0;
			sleep(1000);

			for (int i = 0; i < 2000; i++) {
				motor[motorC] = 15;
				motor[motorB] = -15;
			}
			motor[motorC] = 0;
			motor[motorB] = 0;
			int duration = 0;
			string displayDuration = "";
			while (duration < 2000) {
				motor[motorD] = 10;
				duration += 1;
				stringFormat(displayDuration, "%d", duration);
				displayCenteredBigTextLine(4, displayDuration);
			}
			for (int i = 0; i < 1500; i++) {
				motor[motorC] = 40;
				motor[motorB] = 40;
			}
			motor[motorD] = 0;
			duration = 0;
			sleep(2000);
			while (duration < 2000) {
				motor[motorD] = -10;
				duration += 1;
				stringFormat(displayDuration, "%d", duration);
				displayCenteredBigTextLine(4, displayDuration);
			}
			motor[motorD] = 0;
			motor[motorC] = 0;
			motor[motorB] = 0;
			complete = true;
			for (int i = 0; i < 6000; i++) {
				motor[motorC] = -40;
				motor[motorB] = -40;
			}
		} else {
			for (int i = 0; i < 3000; i++) {
				motor[motorC] = 25;
				motor[motorB] = 25;
			}
		}
	}else {
			if (SensorValue(colorSensor) > 2700) {
			motor[motorC] = -15;
			motor[motorB] = 15;
			sleep(200);
			for (int i = 0; i < 1500; i++) {
				motor[motorC] = 25;
				motor[motorB] = 25;
			}

			stringFormat(value, "%d", SensorValue(colorSensor));
			displayCenteredBigTextLine(4, value);
			}
	}
}

void straightLine() {
	motor[motorC] = 25;
	motor[motorB] = 25;
	if (SensorValue(colorSensor) > 2610 && SensorValue(colorSensor) < 2800) {
			lineFollowing = true;
			greenLinesPassed++;
			for (int i = 0; i < 2000; i++) {
				motor[motorC] = 25;
				motor[motorB] = 25;
			}
		}
}
task main()
{
	while(true) {
		//SensorValue(colorSensor);
		//string value = "";
		//stringFormat(value, "%d", SensorValue(colorSensor));
		//displayCenteredBigTextLine(4, value);
		if (!lineFollowing) {
			straightLine();
		} else {
			followLine();
		}
	}

}
